/**
 * Regenerates app/design-editor.css from design/buildproj/project/Editor.html.
 *
 * Uses the **Sablesteel** theme (Editor.html default via data-theme=sablesteel).
 * Ember :root tokens are discarded.
 *
 * Run: pnpm exec tsx scripts/extract-design-css.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const EDITOR_HTML = path.join(
  process.cwd(),
  "design/buildproj/project/Editor.html",
);
const OUT_CSS = path.join(process.cwd(), "app/design-editor.css");

function extractStyleBlock(html: string): string {
  const m = html.match(/<style>([\s\S]*?)<\/style>/);
  if (!m?.[1]) throw new Error("No <style> block in Editor.html");
  return m[1];
}

function extractSablesteelTokens(css: string): string {
  const m = css.match(/\[data-theme="sablesteel"\]\s*\{([\s\S]*?)\}/);
  if (!m?.[1]) throw new Error("[data-theme=\"sablesteel\"] block not found");
  return m[1]
    .trim()
    .replace(
      /--font-ui:\s*'Inter'[^;]+;/,
      "--font-ui: var(--font-inter), ui-sans-serif, system-ui, sans-serif;",
    )
    .replace(
      /--font-display:\s*'JetBrains Mono'[^;]+;/,
      "--font-display: var(--font-jetbrains-mono), ui-monospace, monospace;",
    )
    .replace(
      /--font-mono:\s*'JetBrains Mono'[^;]+;/,
      "--font-mono: var(--font-jetbrains-mono), ui-monospace, monospace;",
    );
}

function extractSablesteelOverrides(css: string): string {
  const start = css.indexOf("/* Sablesteel — all-caps");
  const end = css.indexOf(".workspace {");
  const section =
    start >= 0 && end > start ? css.slice(start, end) : "";
  const blocks: string[] = [];
  const ruleRe = /\[data-theme="sablesteel"\][^{]+\{[^}]+\}/g;
  let match: RegExpExecArray | null;
  while ((match = ruleRe.exec(section)) !== null) {
    if (match[0].includes("--bg-0:")) continue; // token block
    let rule = match[0].replace(/\[data-theme="sablesteel"\]/g, ".app");
    rule = rule.replace(/\.app\s+body::before/g, ".app::before");
    blocks.push(`    ${rule}`);
  }
  return blocks.length ? `\n/* Sablesteel overrides */\n${blocks.join("\n")}\n` : "";
}

function stripThemes(css: string): string {
  const start = css.indexOf("/* ─── Theme variants");
  const end = css.indexOf(".workspace {");
  if (start >= 0 && end > start) {
    return css.slice(0, start) + css.slice(end);
  }
  return css;
}

function sliceBetween(css: string, startMark: string, endMark: string): string {
  const start = css.indexOf(startMark);
  const end = css.indexOf(endMark);
  if (start >= 0 && end > start) {
    return css.slice(0, start) + css.slice(end);
  }
  return css;
}

function stripUnusedSections(css: string): string {
  css = sliceBetween(css, "/* ─── Note popover", "/* ─── Onboarding");
  css = sliceBetween(css, "/* ─── Onboarding", "/* ─── Unified font");

  const unifiedIdx = css.indexOf("/* ─── Unified font");
  const tightStart = css.indexOf(".density-tight {");
  const microStart = css.indexOf(".density-micro {");

  if (unifiedIdx >= 0 && tightStart > unifiedIdx) {
    const densityTail =
      microStart > tightStart ? css.slice(tightStart, microStart) : css.slice(tightStart);
    css = css.slice(0, unifiedIdx) + densityTail;
  }

  return css;
}

function transformRootAndBody(css: string, tokens: string, sableOverrides: string): string {
  css = css.replace(/:root\s*\{[\s\S]*?\}\s*/, "");

  const appShell = `.app {
${tokens}
  display: flex;
  flex-direction: column;
  height: 100dvh;
  min-height: 0;
  overflow: hidden;
  font-family: var(--font-ui);
  font-size: 13px;
  line-height: 1.45;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
  color: var(--text-0);
  background: var(--bg-0);
  position: relative;
  box-sizing: border-box;
}

.app *,
.app *::before,
.app *::after {
  box-sizing: border-box;
}

`;

  css = css.replace(/\* \{ box-sizing: border-box; \}\s*/g, "");
  css = css.replace(/html, body \{[\s\S]*?\}\s*/g, "");
  css = css.replace(
    /body \{\s*font-size:[\s\S]*?overflow: hidden;\s*\}\s*/g,
    "",
  );

  css = css.replace(/body::before/g, ".app::before");

  css = css.replace(
    /\.app \{ display: flex; flex-direction: column; height: 100vh; min-height: 0; \}\s*/,
    "",
  );

  return appShell + css + sableOverrides;
}

function main() {
  const html = readFileSync(EDITOR_HTML, "utf8");
  let css = extractStyleBlock(html);
  const tokens = extractSablesteelTokens(css);
  const sableOverrides = extractSablesteelOverrides(css);
  css = stripThemes(css);
  css = stripUnusedSections(css);
  css = transformRootAndBody(css, tokens, sableOverrides);

  const header = `/* AUTO-GENERATED by scripts/extract-design-css.ts — do not edit by hand */
/* Source: design/buildproj/project/Editor.html — Sablesteel theme (default in design) */

`;

  writeFileSync(OUT_CSS, header + css.trim() + "\n");
  console.log(`Wrote ${OUT_CSS} (${(header + css).split("\n").length} lines)`);
}

main();
